
clc;clear
close all
codepath = 'H:\ECoG\code_Trange\';
addpath(genpath(codepath));


filepath='H:\ECoG\Activation\3rd\rem_t';
template = fullfile('H:\ECoG\Activation\','2nd','mean_T2.nii');
MaskFile = fullfile('H:\ECoG\Activation\','2nd','lmask_T2.nii');

Colormap(   'statfile',fullfile(filepath,'rem_t.nii'),...
    'bgmfile',template,...
    'slice',13:2:25,...
    'denoi_profile',MaskFile,...
    'bar_value',[-40 -6.5 9.5 40],...
    'dest',filepath,...
    'mapname','rem_t',...
    'adjust_method','FWE',...
    'corrected_p',0.005,...
    'cluster',20);

filepath='H:\ECoG\Activation\3rd\nrem_t';
template = fullfile('H:\ECoG\Activation\','2nd','mean_T2.nii');
MaskFile = fullfile('H:\ECoG\Activation\','2nd','lmask_T2.nii');

Colormap(   'statfile',fullfile(filepath,'nrem_t.nii'),...
    'bgmfile',template,...
    'slice',13:2:25,...
    'denoi_profile',MaskFile,...
    'bar_value',[-20 -3.5 7.5 20],...
    'adjust_method','FWE',...
    'corrected_p',0.05,...
    'dest',filepath,...
    'mapname','nrem_t',...
    'cluster',20);

